services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=workout'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=workout_user'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:8.4.0'
    ports:
      - '6379:6379'
