services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=workout'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=leg_exercise_user'
    ports:
      - '5432:5432'
