spring:
  application:
    name: workout
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    sql: DEBUG
server:
  tomcat:
    accesslog:
      enabled: true
      directory:  # Absolute Path
      pattern: common
